/**
  * Flagr
  * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".
  *
  * OpenAPI spec version: 1.1.13
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package com.crystalxyen.scalaflagr.data

case class EvaluationBatchRequest(
    entities: List[EvaluationEntity],
    enableDebug: Option[Boolean] = None,
    // flagIDs
    flagIDs: Option[List[Long]] = None,
    // flagKeys. Either flagIDs, flagKeys or flagTags works. If pass in multiples, Flagr may return duplicate results.
    flagKeys: Option[List[String]] = None,
    // flagTags. Either flagIDs, flagKeys or flagTags works. If pass in multiples, Flagr may return duplicate results.
    flagTags: Option[List[String]] = None,
    // determine how flagTags is used to filter flags to be evaluated. OR extends the evaluation to those which contains at least one of the provided flagTags or AND limit the evaluation to those which contains all the flagTags.
    flagTagsOperator: Option[String] = None
)
