/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 *
 * OpenAPI spec version: 1.1.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class EvalContext (
  // entityID is used to deterministically at random to evaluate the flag result. If it's empty, flagr will randomly generate one.
  entityID: Option[String] = None,
  entityType: Option[String] = None,
  entityContext: Option[Any] = None,
  enableDebug: Option[Boolean] = None,
  // flagID
  flagID: Option[Long] = None,
  // flagKey. flagID or flagKey will resolve to the same flag. Either works.
  flagKey: Option[String] = None,
  // flagTags. flagTags looks up flags by tag. Either works.
  flagTags: Option[List[String]] = None,
  // determine how flagTags is used to filter flags to be evaluated. OR extends the evaluation to those which contains at least one of the provided flagTags or AND limit the evaluation to those which contains all the flagTags.
  flagTagsOperator: Option[String] = None
)

