/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 *
 * OpenAPI spec version: 1.1.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class PutFlagRequest (
  description: Option[String] = None,
  // enabled data records will get data logging in the metrics pipeline, for example, kafka.
  dataRecordsEnabled: Option[Boolean] = None,
  // it will overwrite entityType into evaluation logs if it's not empty
  entityType: Option[String] = None,
  enabled: Option[Boolean] = None,
  key: Option[String] = None,
  notes: Option[String] = None
)

