/**
  * Flagr
  * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".
  *
  * OpenAPI spec version: 1.1.13
  *
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */
package com.crystalxyen.scalaflagr.model

import java.util.Date

case class Flag(
    id: Option[Long] = None,
    // unique key representation of the flag
    key: Option[String] = None,
    description: String,
    enabled: Boolean,
    tags: Option[List[Tag]] = None,
    segments: Option[List[Segment]] = None,
    variants: Option[List[Variant]] = None,
    // enabled data records will get data logging in the metrics pipeline, for example, kafka.
    dataRecordsEnabled: Boolean,
    // it will override the entityType in the evaluation logs if it's not empty
    entityType: Option[String] = None,
    // flag usage details in markdown format
    notes: Option[String] = None,
    createdBy: Option[String] = None,
    updatedBy: Option[String] = None,
    updatedAt: Option[Date] = None
)
