/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 *
 * OpenAPI spec version: 1.1.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api

import java.text.SimpleDateFormat

import io.swagger.client.model.Distribution
import io.swagger.client.model.Error
import io.swagger.client.model.PutDistributionsRequest
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class DistributionApi(
  val defBasePath: String = "http://localhost/api/v1",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new DistributionApiAsyncHelper(client, config)

  /**
   * 
   * 
   *
   * @param flagID numeric ID of the flag 
   * @param segmentID numeric ID of the segment 
   * @return List[Distribution]
   */
  def findDistributions(flagID: Long, segmentID: Long): Option[List[Distribution]] = {
    val await = Try(Await.result(findDistributionsAsync(flagID, segmentID), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   *  asynchronously
   * 
   *
   * @param flagID numeric ID of the flag 
   * @param segmentID numeric ID of the segment 
   * @return Future(List[Distribution])
   */
  def findDistributionsAsync(flagID: Long, segmentID: Long): Future[List[Distribution]] = {
      helper.findDistributions(flagID, segmentID)
  }

  /**
   * 
   * replace the distribution with the new setting
   *
   * @param flagID numeric ID of the flag 
   * @param segmentID numeric ID of the segment 
   * @param body array of distributions 
   * @return List[Distribution]
   */
  def putDistributions(flagID: Long, segmentID: Long, body: PutDistributionsRequest): Option[List[Distribution]] = {
    val await = Try(Await.result(putDistributionsAsync(flagID, segmentID, body), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   *  asynchronously
   * replace the distribution with the new setting
   *
   * @param flagID numeric ID of the flag 
   * @param segmentID numeric ID of the segment 
   * @param body array of distributions 
   * @return Future(List[Distribution])
   */
  def putDistributionsAsync(flagID: Long, segmentID: Long, body: PutDistributionsRequest): Future[List[Distribution]] = {
      helper.putDistributions(flagID, segmentID, body)
  }

}

class DistributionApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def findDistributions(flagID: Long,
    segmentID: Long)(implicit reader: ClientResponseReader[List[Distribution]]): Future[List[Distribution]] = {
    // create path and map variables
    val path = (addFmt("/flags/{flagID}/segments/{segmentID}/distributions")
      replaceAll("\\{" + "flagID" + "\\}", flagID.toString)
      replaceAll("\\{" + "segmentID" + "\\}", segmentID.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def putDistributions(flagID: Long,
    segmentID: Long,
    body: PutDistributionsRequest)(implicit reader: ClientResponseReader[List[Distribution]], writer: RequestWriter[PutDistributionsRequest]): Future[List[Distribution]] = {
    // create path and map variables
    val path = (addFmt("/flags/{flagID}/segments/{segmentID}/distributions")
      replaceAll("\\{" + "flagID" + "\\}", flagID.toString)
      replaceAll("\\{" + "segmentID" + "\\}", segmentID.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (body == null) throw new Exception("Missing required parameter 'body' when calling DistributionApi->putDistributions")

    val resFuture = client.submit("PUT", path, queryParams.toMap, headerParams.toMap, writer.write(body))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
